[versions]
# ===== Gradle / Kotlin =====
agp = "8.13.2"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.25"

# ===== AndroidX =====
coreKtx = "1.17.0"
lifecycle = "2.9.4"
activityCompose = "1.11.0"
navigation = "2.9.0"
datastore = "1.1.1"
splash = "1.0.1"
# ===== MaterialComponent =====
material = "1.11.0"

# ===== Compose =====
composeBom = "2024.09.00"

# ===== Hilt =====
hilt = "2.52"

# ===== Room =====
room = "2.6.1"

# ===== Network =====
retrofit = "2.11.0"
okhttp = "4.12.0"
gson = "2.11.0"

# ===== Media / Image =====
coil = "2.6.0"
media3 = "1.3.1"

# ===== Accompanist =====
accompanist = "0.35.0"

# ===== Coroutines =====
coroutines = "1.9.0"

# ===== Test =====
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
activity = "1.12.2"
constraintlayout = "2.2.1"


[libraries]
# ===== Core =====
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# ===== Lifecycle =====
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

# ===== Activity =====
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# ===== Material Components =====
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
material = { module = "com.google.android.material:material", version.ref = "material", name = "material" }

# ===== Media3 / ExoPlayer CORE =====
media3Exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3Dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
media3Hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
media3Smooth = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "media3" }
media3Ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3Session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3Common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
androidx-media = { group = "androidx.media", name = "media", version = "1.7.0" }




# ===== Compose =====
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# ===== Navigation =====
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# ===== Hilt =====
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }

# ===== Room =====
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# ===== Network =====
# Retrofit
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# OkHttp
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Gson
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# ===== Coroutines =====
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# ===== Image =====
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# ===== DataStore =====
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }

# ===== Splash =====
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splash" }

# ===== Test =====
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
